// Generated by scripts/linkedin-snapshot.mjs from the LinkedIn data export.
// Do not hand-edit: run `npm run linkedin:snapshot` after downloading a newer
// export. Holds no personal data about anyone else - connections are a COUNT.
const profile = {
  "exportedAt": "2026-07-10",
  "snapshotAt": "2026-10-07",
  "name": "Ravi Kishan",
  "headline": "AI Engineer @ Zimyo | Full Stack Developer | Cloud-Native & Scalable Systems Architect | Multi-Paradigm Programming Expert | Freelancer | VIT’26 MCA",
  "about": "I'm a software engineer drawn to the layers most people take for granted. From scratch I've built a deterministic UI runtime (Relax.js, 1,000+ npm downloads), a programming-language interpreter, a container runtime, and a distributed key-value store — because the fastest way I understand a system is to rebuild it. I'm currently an Agentic AI Engineer at Zimyo, building LangChain/LangGraph agents that turn natural language into multi-step HR workflows; one focus has been driving LLM inference costs down ~70% through schema-constrained prompt design. Previously, as a Quantitative Developer Intern at Arrowhead Capital, I built a vectorized backtesting engine (5M+ records, 4.3× faster) and the data pipelines behind it. I'm also a named inventor on a published Indian patent application for a multilingual RAG system over the Bhagavad Gita, reaching 95%+ retrieval accuracy across five languages. My core interests are distributed systems, systems programming (Go, Rust, C), and applied AI. I've solved 1,200+ algorithmic problems and care about correctness, performance, and clean architecture. Always happy to talk developer tools, infrastructure, and building from first principles.",
  "industry": "Software Development",
  "location": "Samastipur, Bihar, India",
  "websites": "",
  "positions": [
    {
      "company": "Zimyo",
      "title": "AI Engineer",
      "location": "Gurugram",
      "from": "Apr 2026",
      "to": ""
    },
    {
      "company": "ArrowHead Capital Management LLP",
      "title": "Quantitative Developer Intern",
      "location": "Mumbai, Maharashtra, India",
      "from": "Jul 2025",
      "to": "Apr 2026"
    },
    {
      "company": "CHITI INFOTECH PRIVATE LIMITED",
      "title": "Full-stack Developer intern",
      "location": "",
      "from": "Jan 2023",
      "to": "Sep 2023"
    }
  ],
  "education": [
    {
      "school": "Vellore Institute of Technology",
      "degree": "Master of Computer Applications - MCA",
      "from": "Jun 2024",
      "to": "Apr 2026"
    },
    {
      "school": "Prestige Institute of Management & Research, Gwalior",
      "degree": "Bachelor of Computer Application",
      "from": "Jul 2021",
      "to": "Jun 2024"
    },
    {
      "school": "R.S.B.Inter High School",
      "degree": "Higher Secondary Certificate",
      "from": "May 2019",
      "to": "May 2021"
    },
    {
      "school": "R.S.B.Inter High School",
      "degree": "Matriculation Certificate",
      "from": "May 2017",
      "to": "May 2019"
    }
  ],
  "patents": [
    {
      "title": "A Multilingual Chatbot for Indian Epic using Generative AI and Large Language Model",
      "issuer": "202541117128",
      "number": "",
      "filedOn": "Nov 26, 2025",
      "url": ""
    }
  ],
  "skills": {
    "count": 100,
    "sample": [
      "Large-scale Data Analysis",
      "Cloud System",
      "Quantitative Finance",
      "PostCSS",
      "FastAPI",
      "SQLite",
      "Transformers",
      "docker",
      "Bash",
      "Linux",
      "DSA",
      "Software Design"
    ]
  },
  "certifications": 47,
  "projects": 32,
  "languages": 4,
  "volunteering": 2,
  "companiesFollowed": 36,
  "connections": 1148
};

export default profile;
